### ISSUE TITLE
Add example for using a remote non-github/heroku server

### ISSUE THREAD

**Issue by curtisblackwell** [robwierzbowski/grunt-build-control#12]
I've been trying to get this up and running on my server, but can't seem to figure it out. It would be awesome if there was an example or at least links to the necessary info to figure it out.

**Comment by mayur07** [comment]
I Have getting this kind of error.


Pushing gh-pages to git@github.com:username/project_name.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

**Comment by skddc** [comment]
We wrote a blog post a while ago about how to use grunt-build-control with [5apps Deploy](https://5apps.com/deploy), incl. the use of pseudo environments for staging and production:

https://blog.5apps.com/2014/05/29/deploying-static-apps-with-grunt-build-control-on-5apps-deploy.html
