### ISSUE TITLE
Nothing added to commit but untracked files present

### ISSUE THREAD

**Issue by IainAndrew** [robwierzbowski/grunt-build-control#55]
Apologies if this has been answered elsewhere. 

I'm trying to push my dist folder to a new gh-pages branch. When I run `buildcontrol:pages` it creates the gh-pages branch, but tells me there are untracked files - all the files from my master branch. My master branch is up to date. Could someone let me know what's happening here and how I might rectify it?

```
Running "buildcontrol:pages" (buildcontrol) task

Creating remote.

Creating branch "gh-pages".
Switched to a new branch 'gh-pages'

Committing changes to gh-pages.
Warning: On branch gh-pages

Initial commit

Untracked files:
	../.bowerrc
	../.editorconfig
	../.gitattributes
	../.gitignore
	../.jshintrc
	../.travis.yml
	../Gruntfile.js
	../README.md
	../app/
	../bower.json
	../karma-e2e.conf.js
	../karma.conf.js
	../package.json
	../test/

nothing added to commit but untracked files present
 Use --force to continue.

Aborted due to warnings.
```

**Comment by kevinawoo** [comment]
You're source repo still contains untracked files. 

Defaultly, build control connects source commits to dist commits, so you'll need to either have a clean source repo, or set `connectCommits` to false to not check source repo cleanliness.

**Comment by IainAndrew** [comment]
Maybe I'm misunderstanding something, but my source repo *is* clean - when I run `git status` I get:
```
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

When I add and commit the files it asks me to, I run `grunt buildcontrol:pages` and get this error:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

Aborted due to warnings.
```

Any ideas? Thanks, and apologies for my ignorance!

**Comment by kevinawoo** [comment]
Oh no problem, I'm here to help.

If you were to go into the `dist/` folder, and run `git log` you should see the latest commit, correct?

`git remote -v` should return `remote-#####   git@github.com:<username>/<repo name>.git` correct?

Try doing a `git push`. Does the same error `Permission denied (publickey)` occur this time?

**Comment by IainAndrew** [comment]
> If you were to go into the dist/ folder, and run git log you should see the latest commit, correct?
Correct
> git remote -v should return remote-##### git@github.com:<username>/<repo name>.git correct?
Correct
> Try doing a git push. Does the same error Permission denied (publickey) occur this time?
`git push` gives me this:
```
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Everything up-to-date
```
And running `grunt buildcontrol:pages` again gives me the same publickey error.

**Comment by kevinawoo** [comment]
For the warning, you may want to fix that, but it's ok to keep it.

Doesn't seem like you have ability to push to that repo/server. Give this a try
https://help.github.com/articles/error-permission-denied-publickey/

Make sure you can push to the that generated remote name e.g. `remote-203d3`  
`git push remote-203d3 gh-pages`

**Comment by IainAndrew** [comment]
I originally cloned the repo with HTTPS, not SSH, so I'm confused as to why I'm getting an SSH key related error. I can and have been pushing to the master branch for weeks now, I just started getting this error when I tried to use build-control. Do I need to have cloned the repo with SSH?

**Comment by kevinawoo** [comment]
It shouldn't make a difference from clone HTTPS.

You're getting the key error because git cannot connect to the SSH server to push the repo. It could be that the repo `'git@github.com:<username>/<repo name>.git'` does not exist, or the git client is having problems connecting.

Build control does the following (approx):
```
cd dist/
git add .
git checkout gh-pages
git commit -m "blah blah blah blah"
git push remote-2232a gh-pages
```

If you'd like, to see each command, go into `node_modules/grunt-build-control/tasks/build_control.js`  
line 62, short circuit the conditional:
```
        if (true || verbose) {
```

You can see see which command "breaks".

Could you post that log and we'll try to debug it further? (Remember to remove sensitive info!)

**Comment by IainAndrew** [comment]
Sorry, what do you mean by 'short circuit the conditional'? Is 62 the correct line number? I can't see anything relevant on or around that line.
The remote URL is definitely correct, I double checked that several times, haha. 
I tried manually adding, committing and pushing to a new `gh-pages` branch while in the `dist` directory, got the `publickey` error. I can push to a new `gh-pages` branch while in the root directory no problem. Could the fact that I'm .gitignoring `dist` be causing this problem?
Again, thanks so much for your help.

**Comment by kevinawoo** [comment]
"short circuit" just means skipping the conditional.

Shoot, i put the wrong line in there. So Sorry! 
Here's the correct line https://github.com/robwierzbowski/grunt-build-control/blob/master/tasks/build_control.js#L93
Add lines to debug:
```
log.write(command);
log.write(shellResult.output);
```

It sounds like the remote url set in `dist` is incorrect. If you're going to push to the `source` repo's branch `gh-pages` then it should be the `source` directory's remote.

One use case is to have a separate repo to actually contain the `dist`. I do this so when switching branches, I don't remove untracked files.

Ignoring `dist/` in `.gitignore` is perfectly fine. It's recommended, so to keep source repo clean.

**Comment by IainAndrew** [comment]
So I added those lines to `build_control.js` and tried running `grunt buildcontrol:pages`:

```
$ grunt buildcontrol:pages
Running "buildcontrol:pages" (buildcontrol) task

Creating branch "gh-pages".
git checkout --orphan gh-pagesSwitched to a new branch 'gh-pages'
Switched to a new branch 'gh-pages'
git symbolic-ref HEAD refs/heads/gh-pagesgit reset
Committing changes to gh-pages.
git add -A .git commit --file=commitFile-9bbbefOn branch gh-pages

Initial commit

Untracked files:
	../.bowerrc
	../.editorconfig
	../.gitattributes
	../.gitignore
	../.jshintrc
	../.travis.yml
	../Gruntfile.js
	../README.md
	../app/
	../bower.json
	../karma-e2e.conf.js
	../karma.conf.js
	../package.json
	../test/

nothing added to commit but untracked files present
Warning: On branch gh-pages

Initial commit

Untracked files:
	../.bowerrc
	../.editorconfig
	../.gitattributes
	../.gitignore
	../.jshintrc
	../.travis.yml
	../Gruntfile.js
	../README.md
	../app/
	../bower.json
	../karma-e2e.conf.js
	../karma.conf.js
	../package.json
	../test/

nothing added to commit but untracked files present
 Use --force to continue.

Aborted due to warnings.


Execution Time (2015-01-16 09:34:55 UTC)
buildcontrol:pages  3.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 3.4s

$ git add .
$ git commit -m "test"
[gh-pages (root-commit) 0aa11fe] test
 122 files changed, 6601 insertions(+)
 create mode 100644 .bowerrc
 ......lots of files......
 create mode 100644 .editorconfig
$ grunt buildcontrol:pages
Running "buildcontrol:pages" (buildcontrol) task
git symbolic-ref HEAD refs/heads/gh-pagesgit reset
No changes to your branch. Skipping commit.

Pushing gh-pages to git@github.com:<correct-username>/<correct-repo-name>.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
git push remote-###### gh-pagesPermission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

Aborted due to warnings.
```
The `remote-######` it tries to push to is the same remote that `git remote -v

**Comment by kevinawoo** [comment]
[Resolved]

The first issue with the uncommitted files was due to an empty `.git/` folder in `dist/`. Removing it solved this problem.

Second issue was making sure that the public key was added to github.

**Comment by IainAndrew** [comment]
Thanks so much @kevinawoo for all your help!

**Comment by srinivasudadi9000** [comment]
![image](https://cloud.githubusercontent.com/assets/25688281/22852760/59539404-f069-11e6-9110-5ec8991330ed.png)
this page is showing every time

**Comment by victorSousaLopes** [comment]
git add --all       resolve for me

**Comment by Muhammadfarazkhan123** [comment]
it work for me
