### ISSUE TITLE
Nothing added to commit but untracked files present

### ISSUE THREAD

**Issue by JAVEDIQAL** [robwierzbowski/grunt-build-control#65]
I was doing it well until one of my project and Repo. named `GetNetworkAdaptersStats` caused me a trouble :
On applying  `commit -m 'first commit' `
I get:
   
        On branch master

         Initial commit
        
         Untracked files:
                                  GetNetworkAdaptersStats.sln
                                  GetNetworkAdaptersStats.v12.suo
                                 GetNetworkAdaptersStats/ 

      nothing added to commit but untracked files present

PS.Apologies if I'm commiting a duplicated issue because i didn't find a solution to my problem anywhere

**Comment by kevinawoo** [comment]
It sounds like there wasn't added anything to staging area.

Are you running git without grunt-build-control?

**Comment by kevinawoo** [comment]
closing request, please reopen if there's further issues.
