### ISSUE TITLE
Clone with custom config

### ISSUE THREAD

**Issue by brunowego** [robwierzbowski/grunt-build-control#66]
I have a specific case where I need clone with this follow config:

```bash
git config http.sslVerify false
```

Any idea how do this? Thanks!

**Comment by brunowego** [comment]
I have tried with this config, but not works:

```js
// Automated deploy task
module.exports = {
  options: {
    commit: true,
    push: true,
    message: 'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%',
    connectCommits: false,
    config: {
      'http.sslVerify': false
    }
  },
  dist: {
    ... 
  }
};
```

**Comment by kevinawoo** [comment]
I'm stumped, I just added a test case to verify that it works. 026f73a4836ddc8b61de20d1b38dcc6a682182d6

**Comment by kevinawoo** [comment]
It just dawned on me, are you trying to add the options after dist repo was initialized? 

If so, a quick fix would be to delete `dist/.git` folder and have build control init it again. 

I'll make a fix for it as soon as I got time.

**Comment by brunowego** [comment]
Works like a charm! Thanks.
