### ISSUE TITLE
Cannot commit and push my files into github

### ISSUE THREAD

**Issue by etotientz** [robwierzbowski/grunt-build-control#67]
Whenever $ git push -u origin master is being typed this is shown::
ssh:connect to host github.com port 22:Bad file number
fatal:Could not read from remote repository.
I do not understand why this is happening everytime.I am able to initialise git ,git add . and $git remote add origin git@github.com:etotientz/Hello.git. So,please clarify the error.

**Comment by kevinawoo** [comment]
Here's the info I grabbed from github:
https://help.github.com/articles/error-bad-file-number/

Can you `ssh -vT git@github.com` and make sure you get the same error?
Try making sure that you can reach github with ssh https://help.github.com/articles/generating-ssh-keys/

make suer you can do a `git push` to the remote from the `dist/` folder.

**Comment by kevinawoo** [comment]
Closing request, please reopen if the problem persists!
