### ISSUE TITLE
Build control swallows git diff output when checking requirements

### ISSUE THREAD

**Issue by davidjb** [robwierzbowski/grunt-build-control#73]
The call to `git diff` at https://github.com/robwierzbowski/grunt-build-control/blob/master/tasks/build_control.js#L135 only checks whether the output from the command is non-empty before throwing the uncommitted changes error on the following line.

I've had a situation where a line endings were being adjusted by Git and the output of `git diff` was:

```
warning: CRLF will be replaced by LF in dist/images/flag.svg.
The file will have its original line endings in your working directory.
```

Easy enough to fix, but hard to actually determine as buildcontrol doesn't log the result of the `git diff` command; it only performs the "is empty" check and then assumes all non-empty results must be due to uncommitted changes.

My suggestion is to log the output from `git diff` so users can easily identify and resolve their issue.  Adjusting the error message thrown would also help in ensuring users aren't misled into looking for uncommitted changes.

**Comment by kevinawoo** [comment]
Sounds like a pretty good idea. I'll give it some work.

**Comment by davidjb** [comment]
Great, thanks! That'll make determining the cause of commit failures that
much simpler.
