### ISSUE TITLE
Clean push wipes existing branch files

### ISSUE THREAD

**Issue by kamranayub** [robwierzbowski/grunt-build-control#82]
I am using this plugin to separate our core work from compiled dists. I noticed on a clean build (i.e. no build output), the plugin will successfully fetch the remote branch but will end up deleting existing content on the branch besides build output.

It seems like perhaps the plugin needs to temporarily copy any files in the folder somewhere, clean the directory, fetch the remote branch, then copy the output back to ensure it either overwrites or adds content.

Here's an example:

Dist commit that wipes existing files: https://github.com/excaliburjs/excalibur-dist/commit/2ac9d0b752133b344003e52f3cbbb71781e700fd

Travis CI output:

```
Running "buildcontrol:dist" (buildcontrol) task

Creating git repository in "build".
Initialized empty Git repository in /home/travis/build/excaliburjs/Excalibur/build/.git/

Creating remote.

Fetching "test" history from https://<CREDENTIALS>@github.com/excaliburjs/excalibur-dist.
Branch test set up to track remote branch test from remote-c9c835.

Committing changes to "test".
[test 2ac9d0b] :shipit: Built excalibur from commit 8d2684b on branch HEAD
 6 files changed, 1 insertion(+), 170 deletions(-)
 delete mode 100644 .gitattributes
 delete mode 100644 .gitignore
 delete mode 100644 LICENSE.md
 delete mode 100644 README.md
 delete mode 100644 bower.json
 create mode 100644 dist/excalibur.min.js.map

Pushing test to https://<CREDENTIALS>@github.com/excaliburjs/excalibur-dist
```

Here's my task:

```
buildcontrol: {
         options: {
            dir: 'build',                     
            commit: true,
            push: true,
            message: ':shipit: Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%',
            config: {
               'user.name': 'Travis-CI',
               'user.email': 'travis@excaliburjs.com'
            }
         },

         // continuous integration dists
         dist: {
            options: {
               branch: 'test', // TODO change to master when tested
               remote: 'https://github.com/excaliburjs/excalibur-dist',
               login: 'kamranayub',
               token: process.env.GH_DIST_TOKEN,
               fetchProgress: false
            }
         }
      },
```

Is this expected?

In my case, the repo is organized like:

```
- dist/
- README
- LICENSE
- bower.json
```

And I only copy compiled output to the `dist` folder.

I can workaround this by ensuring I clone the repository *before* copying my build output and then it works but I expected the plugin to gracefully handle a from-scratch build (e.g. on our CI server) without any custom workaround.

**Comment by kevinawoo** [comment]
I think it might be best to clone the repo **before** copying the build output, otherwise build-control will think the build was to remove 1 or more (or in this case all) files.

If this is a bigger issue rather than a minor annoyance, we'll try to add a work around.

**Comment by kamranayub** [comment]
That's fine, I could definitely see it being complex to add this logic to the plugin (since the plugin runs after copying, you'd need to diff or do some crazy stuff).

**Comment by dpolivy** [comment]
I'm running into a similar issue. I'm looking at using `grunt-build-control` to save versioned (hashed) files for distribution on a CDN. But, I want to have multiple other directories in the remote repo that aren't necessarily built locally, and I also want to preserve existing versioned files in the repo -- essentially, each commit to the repo should be a brand new file.

Is there a good reliable solution for this scenario? Do I just need to force a sync of the dist directory prior to copying the built files? Would be great if this were an option as part of the "Fetching <branch> history" step.

**Comment by kevinawoo** [comment]
@dpolivy it sounds like you can just commit each new file into `dist` without touching the old file and it should achieve what you need it to.

**Comment by dpolivy** [comment]
@kevinawoo Yes, but "cleaning" the dist dir has the unintended side effect of deleting all OTHER files from the repo.

I actually worked out a solution that seems to work using the `grunt-git` plugin; as part of the build step I will clean the build dir, sync it, reset all changes, and then do my build. That seems to get the job done of ensuring files don't get deleted unintentionally.

It would be nice if this functionality (ability to sync and checkout latest files) were part of `grunt-build-control`.

**Comment by kevinawoo** [comment]
@dpolivy it should be pulling and merging and not `cleaning`.

**Comment by dpolivy** [comment]
@kevinawoo In my experience, since there are files in the repo that are not built each time, if I clean my dist directory, and then run buildcontrol, it does not pull and checkout the files in the repo. Basically, all existing files end up getting deleted (this seems to be the original issue @kamranayub cited above).
